### ISSUE TITLE
Need API endpoints response status code list

### ISSUE THREAD

**Issue by davipon** [davipon/snowball#10]
@AdrieneTZ We need to align the response status code:

`200` means successful
`400` means a bad request (e.g., incorrect format)

Others like wrong credentials, ...etc.

**Comment by davipon** [comment]
For the first draft of the use of status code, I'd suggest:

- [`200 OK`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200)
- [`201 Created`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201): `POST`
- [`204 No Content`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204): `PUT` or `DELETE`
- [`400 Bad Request`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400): Wrong request body
- [`401 Unauthorized`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401): Invalid credential (not logged in but send request)

**Comment by AdrieneTZ** [comment]
Thank you for the suggestion. After adding auth process, I will add the status code on each response.

**Comment by davipon** [comment]
Good job! @AdrieneTZ .
